imports:
    - { resource: tables.yml }
services:
    flerex.linkedaccounts.listener:
        class: flerex\linkedaccounts\event\main_listener
        arguments:
            - '@user'
            - '@auth'
            - '@template'
            - '@controller.helper'
            - '@flerex.linkedaccounts.utils'
        tags:
            - { name: event.listener }
    flerex.linkedaccounts.utils:
        class: flerex\linkedaccounts\service\utils
        arguments:
            - '@user'
            - '@dbal.conn'
            - '%flerex.linkedaccounts.tables.links%'
    flerex.linkedaccounts.switcher:
        class: flerex\linkedaccounts\controller\switcher
        arguments:
            - '@user'
            - '@auth'
            - '@flerex.linkedaccounts.utils'
